version: "3.8"

services:

  db:
    image: library/postgres:13.0-alpine
    container_name: db
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "0.0.0.0:5432:5432"

  api:
    build: ./api
    ports:
      - "0.0.0.0:5000:5000"
    env_file:
      - .env

  crawlers:
    build: ./api
    restart: "no"
    env_file:
      - .env
    entrypoint: /bin/bash -c "flask parse"
