"""Delete all product's reviews on CASCADE

Revision ID: fa5a21b5806e
Revises: 1a02f4a32e14
Create Date: 2020-11-04 21:51:05.793359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5a21b5806e'
down_revision = '1a02f4a32e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_product_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_product_id_fkey', 'review', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
